function [M,b] = applyMechBC(M,b,mu,H,tau_base,north,south,east,west,m,dy,dz)
%Applies boundary conditions to the ice stream mechanical model

%North (stress-free)
BCn = [north,...
       ones(length(north),1),...
       mu(north),...
       sparse(length(north),1),...
       sparse(length(north),1)];
%BCr: [[node numbers], [a], [mu], [b], [c]]
[M,b] = applyRobin(M,b,BCn,-m,dz);

%South (Robin)
BCs = [south,...
       (1./mu(south)).*(1-H) + 1e-100,...
       mu(south),...
       H,...
       (tau_base(south)./mu(south)).*(1-H)];
%BCr: [[node numbers], [a], [mu], [b], [c]]
[M,b] = applyRobin(M,b,BCs,m,dz);

%East (symmetry)
BCe = [east,...
       ones(length(east),1),...
       mu(east),...
       sparse(length(east),1),...
       sparse(length(east),1)];
%BCr: [[node numbers], [a], [mu], [b], [c]]
[M,b] = applyRobin(M,b,BCe,-1,dy);

%West (symmetry)
BCw = [west,...
       ones(length(west),1),...
       mu(west),...
       sparse(length(west),1),...
       sparse(length(west),1)];
%BCr: [[node numbers], [a], [mu], [b], [c]]
[M,b] = applyRobin(M,b,BCw,1,dy);

end

